services:
  mongodb:
    image: "mongo:4.4"
    volumes:
      - ../DataDB:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: GetPlace
    ports:
      - "27018:27017"

  getplacebackend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5211
      - MONGO_CONN=mongodb://root:secret@mongodb:27017
      - APP_UID=0
    ports:
      - "5211:5211"
    depends_on:
      - mongodb

